version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 14
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - aws s3 sync build/ s3://bakare-bucket
      - aws cloudfront create-invalidation --distribution-id E3JYLG9L0D0086 --paths "/*"

artifacts:
  files: '**/*'
  name: my-artifact-name
