version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - yern install
  build:
    commands:
      - yern run build
  post_build:
    commands:
      - aws s3 sync build/ s3://your-s3-bucket
      - aws cloudfront create-invalidation --distribution-id E3JYLG9L0D0086 --paths "/*"

artifacts:
  files: '**/*'
  name: my-artifact-name
