version: 0.2

phases:
  install:
    runtime-version:
      nodejs: 18
  pre_build:
    commands:
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - source ~/.nvm/nvm.sh
      - nvm install 18
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync build/ s3://bakare-bucket
      - aws cloudfront create-invalidation --distribution-id E3JYLG9L0D0086 --paths "/*"

artifacts:
  files: '**/*'
  name: my-artifact-name
